spring:
  config.activate.on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/accounting
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        rewriteBatchedInserts: true
